trigger:
- master

name: Core-$(Date:yyy.MM)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:  
  projectsToBuild: '**/*.csproj'
  configuration: Release
  platform: 'Any CPU'
  system.debug: 'true'
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: 'build'
    projects: '$(projectsToBuild)'
    arguments: '-c $(configuration) -p:Platform=$(platform)'