trigger:
- master

name: Core-$(Date:yyy.M)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:  
  projectsToBuild: '**/*.csproj'
  configuration: Release
  platform: 'Any CPU'
  system.debug: 'true'
  nuggetsDirectory: $(Build.ArtifactStagingDirectory)\Nuggets
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    arguments: '-r:False -noLogo'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: pack
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    arguments: '-r:False -noLogo --no-build -o $(nuggetsDirectory)'

