trigger:
- master

name: Core-$(Date:yyy.M)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:  
  projectsToBuild: '**/*.csproj'
  configuration: Release
  platform: 'Any CPU'
  system.debug: 'true'
  nuggetsDirectory: $(Build.ArtifactStagingDirectory)\Nuggets
  nuggetsToPush: $(nuggetsDirectory)\Core*.nupkg
  version: ''
  
steps:
- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    arguments: '-noLogo'
    feedsToUse: select
    vstsFeed: 'Nuggets'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: pack
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    arguments: '-noLogo --no-build -o $(nuggetsDirectory)'
- task: DotNetCoreCLI@2
  displayName: Push Packages to Nuggets
  inputs:
    command: push
    nobuild: true
    arguments: '-noLogo'
    packagesToPush: $(nuggetsToPush)
    nuGetFeedType: internal
    publishVstsFeed: 'Nuggets'
