trigger:
- master

name: Core-$(Date:yyy.M)$(Rev:.r)

pool:
  vmImage: 'windows-latest'

variables:  
  projectsToBuild: '**/*.csproj'
  projectsToPack: '**/*.csproj;!**/*Test*.csproj;'
  configuration: Release
  platform: 'Any CPU'
  system.debug: 'true'
  nuggetsDirectory: $(Build.ArtifactStagingDirectory)\Nuggets
  nuggetsToPush: $(nuggetsDirectory)\Core*.nupkg
  version: ''
  
steps:
- task: UseDotNet@2
  displayName: Use dotnet 2.2.x
  inputs:
    packageType: 'sdk'
    version: '2.2.402'

- task: PowerShell@2
  displayName: Prepare Version Number
  inputs:
    targetType: 'inline'
    script: |
      $version = $env:BUILD_BUILDNUMBER.Substring($env:BUILD_BUILDNUMBER.IndexOf('-')+1);
      Write-Host "##vso[task.setvariable variable=version;]$version";
      
- task: DotNetCoreCLI@2
  displayName: Restore
  inputs:
    command: restore
    nobuild: true
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    feedsToUse: select
    vstsFeed: 'Nuggets'

- task: DotNetCoreCLI@2
  displayName: Build
  inputs:
    command: build
    projects: '$(projectsToBuild)'
    configuration: $(configuration)
    arguments: '-noLogo --no-restore -p:Version=$(version)'
    
- task: DotNetCoreCLI@2
  displayName: Pack
  inputs:
    command: custom
    custom: pack
    projects: '$(projectsToPack)'
    configuration: $(configuration)
    arguments: '-noLogo --no-build -p:PackageVersion=$(version) -o $(nuggetsDirectory)'

- task: DotNetCoreCLI@2
  displayName: Push Packages to Nuggets
  inputs:
    command: push
    nobuild: true
    arguments: '-noLogo'
    packagesToPush: $(nuggetsToPush)
    nuGetFeedType: internal
    publishVstsFeed: 'Nuggets'
